package interfaces;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

import core.algorithms.AlgorithmException;
import core.algorithms.AlgorithmManager;
import inevaup.dialogs.InfoDialog;
import sketch.DrawMode;
import sketch.FeedBackObserver;
import sketch.GraphSketch;

public class ControlInterface extends javax.swing.JFrame implements FeedBackObserver {

    private GraphSketch graphSketch;

    private final Color MAIN_COLOR = new Color(180, 10, 9);
    private final Color PRIMARY_TEXT = new Color(33, 33, 33);
    private final Color BACKGROUND_COLOR = new Color(247, 247, 250);
    private boolean[] activeButtonGroup = { true, false, false };
    private javax.swing.JPanel[] buttonGroup;
    private javax.swing.JLabel[] labelGroup;

    private AlgorithmManager algorithmManager;

    public ControlInterface() {
        initComponents();

        graphSketch = new GraphSketch();
        graphSketch.run();

        buttonGroup = new javax.swing.JPanel[] { draw_node_mode_button, draw_edge_mode_button,
                undraw_node_mode_button, };
        labelGroup = new javax.swing.JLabel[] { draw_node_mode_label, draw_edge_mode_label, undraw_node_mode_label, };

        centreWindows();
        updateButtonGroup(0, null);
        graphSketch.getGraphDrawer().setFeedBackObserver(this);
        algorithmManager = new AlgorithmManager(graphSketch.getGraphDrawer().getGraph());
    }

    @Override
    public void onNewMessage(String message) {
        String base = "<html>Info: %s</html>";
        feedback_label.setText(String.format(base, message));
    }

    @Override
    public void onGraphChange() {
        algorithmManager.buildMatrix();
    }

    public void updateButtonGroup(int activeIndex, DrawMode drawMode) {
        activeButtonGroup[activeIndex] = true;
        for (int i = 0; i < activeButtonGroup.length; i++) {
            activeButtonGroup[i] = false;
            if (i == activeIndex) {
                activeButtonGroup[i] = true;
            }
        }
        for (int i = 0; i < activeButtonGroup.length; i++) {
            if (activeButtonGroup[i]) {
                buttonGroup[i].setBackground(MAIN_COLOR);
                labelGroup[i].setForeground(Color.WHITE);
            } else {
                buttonGroup[i].setBackground(BACKGROUND_COLOR);
                labelGroup[i].setForeground(PRIMARY_TEXT);
            }
        }
        if (drawMode != null) {
            graphSketch.getGraphDrawer().onChangeDrawMode(drawMode, command_input.getText());
        }
    }

    public GraphSketch getSketch() {

        return graphSketch;
    }

    private void centreWindows() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();

        int windownsGap = 30;
        int horizontalGap = (int) ((dimension.getWidth() - graphSketch.SKETCH_WIDTH - this.getWidth() - windownsGap)
                / 2);

        this.setLocation(horizontalGap, (int) ((dimension.getHeight() - this.getHeight()) / 2));

        graphSketch.getSurface().setLocation(horizontalGap + this.getWidth() + windownsGap,
                (int) ((dimension.getHeight() - graphSketch.SKETCH_HEIGHT) / 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        help = new javax.swing.JButton();
        divider3 = new javax.swing.JPanel();
        divider1_label2 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        command_input_label = new javax.swing.JLabel();
        command_input = new javax.swing.JTextField();
        mode_label = new javax.swing.JLabel();
        command_input_container1 = new javax.swing.JPanel();
        draw_node_mode_button = new javax.swing.JPanel();
        draw_node_mode_label = new javax.swing.JLabel();
        draw_edge_mode_button = new javax.swing.JPanel();
        draw_edge_mode_label = new javax.swing.JLabel();
        undraw_node_mode_button = new javax.swing.JPanel();
        undraw_node_mode_label = new javax.swing.JLabel();
        feedback_label = new javax.swing.JLabel();
        divider4 = new javax.swing.JPanel();
        divider1_label3 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        init_node_name_label = new javax.swing.JLabel();
        init_node_name_input = new javax.swing.JTextField();
        algo_container1 = new javax.swing.JPanel();
        draw_edge_mode_button2 = new javax.swing.JPanel();
        draw_edge_mode_label2 = new javax.swing.JLabel();
        draw_node_mode_button2 = new javax.swing.JPanel();
        draw_node_mode_label2 = new javax.swing.JLabel();
        undraw_node_mode_button2 = new javax.swing.JPanel();
        undraw_node_mode_label2 = new javax.swing.JLabel();
        undraw_node_mode_button3 = new javax.swing.JPanel();
        undraw_node_mode_label3 = new javax.swing.JLabel();
        divider2 = new javax.swing.JPanel();
        divider1_label1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        opt_container = new javax.swing.JPanel();
        draw_edge_mode_button6 = new javax.swing.JPanel();
        draw_edge_mode_label34 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        output_textarea = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(247, 249, 249));

        header.setBackground(new java.awt.Color(180, 10, 9));

        title_label.setBackground(new java.awt.Color(55, 71, 79));
        title_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        title_label.setForeground(new java.awt.Color(255, 255, 255));
        title_label.setText("Servicio de internet");
        title_label.setIconTextGap(15);

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help_mini2.jpg"))); // NOI18N
        help.setBorderPainted(false);
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help.setPreferredSize(new java.awt.Dimension(48, 25));
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(help, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_label))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        divider3.setBackground(new java.awt.Color(248, 249, 250));

        divider1_label2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        divider1_label2.setForeground(new java.awt.Color(117, 117, 117));
        divider1_label2.setText("Creación del grafo");

        jSeparator11.setForeground(new java.awt.Color(117, 117, 117));

        jSeparator12.setForeground(new java.awt.Color(117, 117, 117));

        javax.swing.GroupLayout divider3Layout = new javax.swing.GroupLayout(divider3);
        divider3.setLayout(divider3Layout);
        divider3Layout.setHorizontalGroup(
            divider3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divider3Layout.createSequentialGroup()
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(divider1_label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        divider3Layout.setVerticalGroup(
            divider3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divider3Layout.createSequentialGroup()
                .addGroup(divider3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(divider3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(divider3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divider3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(divider1_label2)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        command_input_label.setBackground(new java.awt.Color(248, 249, 250));
        command_input_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        command_input_label.setForeground(new java.awt.Color(33, 33, 33));
        command_input_label.setText("Nombre o peso");
        command_input_label.setIconTextGap(12);

        command_input.setColumns(7);
        command_input.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        command_input.setForeground(new java.awt.Color(33, 33, 33));
        command_input.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        command_input.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 189, 189)), javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7)));
        command_input.setMargin(new java.awt.Insets(10, 10, 10, 10));
        command_input.setName(""); // NOI18N
        command_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                OnCommandInputChange(evt);
            }
        });

        mode_label.setBackground(new java.awt.Color(248, 249, 250));
        mode_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mode_label.setForeground(new java.awt.Color(33, 33, 33));
        mode_label.setText("Modos");
        mode_label.setIconTextGap(12);

        command_input_container1.setBackground(new java.awt.Color(248, 249, 250));

        draw_node_mode_button.setBackground(new java.awt.Color(180, 10, 9));
        draw_node_mode_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        draw_node_mode_button.setName("Home"); // NOI18N
        draw_node_mode_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnDrawNode(evt);
            }
        });
        draw_node_mode_button.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        draw_node_mode_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        draw_node_mode_label.setForeground(new java.awt.Color(255, 255, 255));
        draw_node_mode_label.setText("Agregar Nodo");
        draw_node_mode_label.setIconTextGap(15);
        draw_node_mode_button.add(draw_node_mode_label);

        command_input_container1.add(draw_node_mode_button);

        draw_edge_mode_button.setBackground(new java.awt.Color(180, 10, 9));
        draw_edge_mode_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        draw_edge_mode_button.setName("Home"); // NOI18N
        draw_edge_mode_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnDrawEdge(evt);
            }
        });
        draw_edge_mode_button.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        draw_edge_mode_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        draw_edge_mode_label.setForeground(new java.awt.Color(255, 255, 255));
        draw_edge_mode_label.setText("Agregar Arista");
        draw_edge_mode_label.setIconTextGap(15);
        draw_edge_mode_button.add(draw_edge_mode_label);

        command_input_container1.add(draw_edge_mode_button);

        undraw_node_mode_button.setBackground(new java.awt.Color(180, 10, 9));
        undraw_node_mode_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        undraw_node_mode_button.setName("Home"); // NOI18N
        undraw_node_mode_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnUnDrawNode(evt);
            }
        });
        undraw_node_mode_button.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        undraw_node_mode_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        undraw_node_mode_label.setForeground(new java.awt.Color(255, 255, 255));
        undraw_node_mode_label.setText("Remover Nodo");
        undraw_node_mode_label.setIconTextGap(15);
        undraw_node_mode_button.add(undraw_node_mode_label);

        command_input_container1.add(undraw_node_mode_button);

        feedback_label.setBackground(new java.awt.Color(248, 249, 250));
        feedback_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        feedback_label.setForeground(new java.awt.Color(33, 33, 33));
        feedback_label.setText("Info: Haz click en el lienzo para crear un nodo");
        feedback_label.setIconTextGap(12);

        divider4.setBackground(new java.awt.Color(248, 249, 250));

        divider1_label3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        divider1_label3.setForeground(new java.awt.Color(117, 117, 117));
        divider1_label3.setText("Algoritmos");

        jSeparator13.setForeground(new java.awt.Color(117, 117, 117));

        jSeparator14.setForeground(new java.awt.Color(117, 117, 117));

        javax.swing.GroupLayout divider4Layout = new javax.swing.GroupLayout(divider4);
        divider4.setLayout(divider4Layout);
        divider4Layout.setHorizontalGroup(
            divider4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divider4Layout.createSequentialGroup()
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(divider1_label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13)
                .addContainerGap())
        );
        divider4Layout.setVerticalGroup(
            divider4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divider4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(divider4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divider1_label3, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        init_node_name_label.setBackground(new java.awt.Color(248, 249, 250));
        init_node_name_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        init_node_name_label.setForeground(new java.awt.Color(33, 33, 33));
        init_node_name_label.setText("Nombre Nodo");
        init_node_name_label.setIconTextGap(12);

        init_node_name_input.setColumns(7);
        init_node_name_input.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        init_node_name_input.setForeground(new java.awt.Color(33, 33, 33));
        init_node_name_input.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        init_node_name_input.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 189, 189)), javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7)));
        init_node_name_input.setMargin(new java.awt.Insets(10, 10, 10, 10));
        init_node_name_input.setName(""); // NOI18N

        algo_container1.setBackground(new java.awt.Color(248, 249, 250));

        draw_edge_mode_button2.setBackground(new java.awt.Color(180, 10, 9));
        draw_edge_mode_button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        draw_edge_mode_button2.setName("Home"); // NOI18N
        draw_edge_mode_button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnDfs(evt);
            }
        });
        draw_edge_mode_button2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        draw_edge_mode_label2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        draw_edge_mode_label2.setForeground(new java.awt.Color(255, 255, 255));
        draw_edge_mode_label2.setText("DFS");
        draw_edge_mode_label2.setIconTextGap(15);
        draw_edge_mode_button2.add(draw_edge_mode_label2);

        algo_container1.add(draw_edge_mode_button2);

        draw_node_mode_button2.setBackground(new java.awt.Color(180, 10, 9));
        draw_node_mode_button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        draw_node_mode_button2.setName("Home"); // NOI18N
        draw_node_mode_button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnBFS(evt);
            }
        });
        draw_node_mode_button2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        draw_node_mode_label2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        draw_node_mode_label2.setForeground(new java.awt.Color(255, 255, 255));
        draw_node_mode_label2.setText("BFS");
        draw_node_mode_label2.setIconTextGap(15);
        draw_node_mode_button2.add(draw_node_mode_label2);

        algo_container1.add(draw_node_mode_button2);

        undraw_node_mode_button2.setBackground(new java.awt.Color(180, 10, 9));
        undraw_node_mode_button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        undraw_node_mode_button2.setName("Home"); // NOI18N
        undraw_node_mode_button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnDij(evt);
            }
        });
        undraw_node_mode_button2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        undraw_node_mode_label2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        undraw_node_mode_label2.setForeground(new java.awt.Color(255, 255, 255));
        undraw_node_mode_label2.setText("Menor Costo");
        undraw_node_mode_label2.setIconTextGap(15);
        undraw_node_mode_button2.add(undraw_node_mode_label2);

        algo_container1.add(undraw_node_mode_button2);

        undraw_node_mode_button3.setBackground(new java.awt.Color(180, 10, 9));
        undraw_node_mode_button3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        undraw_node_mode_button3.setName("Home"); // NOI18N
        undraw_node_mode_button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onMainTorre(evt);
            }
        });
        undraw_node_mode_button3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        undraw_node_mode_label3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        undraw_node_mode_label3.setForeground(new java.awt.Color(255, 255, 255));
        undraw_node_mode_label3.setText("Torre principal");
        undraw_node_mode_label3.setIconTextGap(15);
        undraw_node_mode_button3.add(undraw_node_mode_label3);

        algo_container1.add(undraw_node_mode_button3);

        divider2.setBackground(new java.awt.Color(248, 249, 250));

        divider1_label1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        divider1_label1.setForeground(new java.awt.Color(117, 117, 117));
        divider1_label1.setText("Opciones de Sketch");

        jSeparator9.setForeground(new java.awt.Color(117, 117, 117));

        jSeparator10.setForeground(new java.awt.Color(117, 117, 117));

        javax.swing.GroupLayout divider2Layout = new javax.swing.GroupLayout(divider2);
        divider2.setLayout(divider2Layout);
        divider2Layout.setHorizontalGroup(
            divider2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divider2Layout.createSequentialGroup()
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(divider1_label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9)
                .addContainerGap())
        );
        divider2Layout.setVerticalGroup(
            divider2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divider2Layout.createSequentialGroup()
                .addGroup(divider2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(divider2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(divider2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divider2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(divider1_label1)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        opt_container.setBackground(new java.awt.Color(248, 249, 250));

        draw_edge_mode_button6.setBackground(new java.awt.Color(180, 10, 9));
        draw_edge_mode_button6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        draw_edge_mode_button6.setName("Home"); // NOI18N
        draw_edge_mode_button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeMap(evt);
            }
        });
        draw_edge_mode_button6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        draw_edge_mode_label34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        draw_edge_mode_label34.setForeground(new java.awt.Color(255, 255, 255));
        draw_edge_mode_label34.setText("Cambiar Mapa");
        draw_edge_mode_label34.setIconTextGap(15);
        draw_edge_mode_button6.add(draw_edge_mode_label34);

        opt_container.add(draw_edge_mode_button6);

        output_textarea.setEditable(false);
        output_textarea.setBackground(new java.awt.Color(238, 238, 238));
        output_textarea.setColumns(20);
        output_textarea.setRows(5);
        output_textarea.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        output_textarea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jScrollPane2.setViewportView(output_textarea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(command_input_label, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(command_input, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mode_label, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(init_node_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(init_node_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(feedback_label, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(divider2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opt_container, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(divider4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(algo_container1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(divider3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(command_input_container1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(command_input_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(command_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mode_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(feedback_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(divider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(init_node_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(init_node_name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(algo_container1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(divider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(562, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(221, 221, 221)
                    .addComponent(command_input_container1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(389, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeMap(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_changeMap
        int scene = graphSketch.getActualScene();
        if (scene != 0) {
            graphSketch.setScene(0);
        }
    }// GEN-LAST:event_changeMap

    private void OnCommandInputChange(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_OnCommandInputChange
        graphSketch.getGraphDrawer().onChangeDrawMode(
            graphSketch.getGraphDrawer().getDrawMode(),
            command_input.getText()
        );
    }// GEN-LAST:event_OnCommandInputChange

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_helpActionPerformed
        HelpDialog helpDialog = new HelpDialog(this, true);
        helpDialog.setVisible(true);
    }// GEN-LAST:event_helpActionPerformed

    private void OnDfs(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_OnDfs
        try {
            String output = algorithmManager.executeDFS();
            output_textarea.setText(output);
        } catch (AlgorithmException e) {
            InfoDialog infoDialog = new InfoDialog(
                null, 
                "Error", 
                e.getReason(),
                InfoDialog.TypeInfoDialog.ERROR_DIALOG
            );
              infoDialog.setVisible(true);
        }
    }// GEN-LAST:event_OnDfs

    private void OnBFS(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_OnBFS
        try {
            String output = algorithmManager.executeBFS();
            output_textarea.setText(output);
        } catch (AlgorithmException e) {
           
            InfoDialog infoDialog = new InfoDialog(
                null, 
                "Error", 
                e.getReason(),
                InfoDialog.TypeInfoDialog.ERROR_DIALOG
            );
            infoDialog.setVisible(true);
        }
    }// GEN-LAST:event_OnBFS

    private void OnDij(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_OnDij
        try {
            String output;
            if (init_node_name_input.getText().equals("")){
                output = algorithmManager.executeShortestPathToAllNodes();
            }else{
                output = algorithmManager.executeShortestPath(
                    init_node_name_input.getText()
                );
            }
            output_textarea.setText(output);
        } catch (AlgorithmException e) {
            
             InfoDialog infoDialog = new InfoDialog(
                null, 
                "Error", 
                e.getReason(),
                InfoDialog.TypeInfoDialog.ERROR_DIALOG
            );
            infoDialog.setVisible(true);
           
        }
    }// GEN-LAST:event_OnDij

    private void onMainTorre(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_onMainTorre
        boolean isSuccessful = algorithmManager.setMainTowerName(
            init_node_name_input.getText()
        );
        if (!isSuccessful) {
            InfoDialog infoDialog = new InfoDialog(
                null, 
                "Error", 
                "El nodo escrito no existe",
                InfoDialog.TypeInfoDialog.ERROR_DIALOG
            );
            infoDialog.setVisible(true);
        }else{
            InfoDialog infoDialog = new InfoDialog(
                null, 
                "Exito", 
                "La torre principal es: " + init_node_name_input.getText(),
                InfoDialog.TypeInfoDialog.SUCCESS_DIALOG
            );
            infoDialog.setVisible(true);
        }
    }// GEN-LAST:event_onMainTorre

    private void OnDrawEdge(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_OnDrawEdge
        updateButtonGroup(1, DrawMode.DRAW_EDGE);
    }// GEN-LAST:event_OnDrawEdge

    private void OnDrawNode(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_OnDrawNode
        updateButtonGroup(0, DrawMode.DRAW_NODE);
    }// GEN-LAST:event_OnDrawNode

    private void OnUnDrawNode(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_OnUnDrawNode
        updateButtonGroup(2, DrawMode.UNDRAW_NODE);
    }// GEN-LAST:event_OnUnDrawNode

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlInterface().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel algo_container1;
    private javax.swing.JTextField command_input;
    private javax.swing.JPanel command_input_container1;
    private javax.swing.JLabel command_input_label;
    private javax.swing.JLabel divider1_label1;
    private javax.swing.JLabel divider1_label2;
    private javax.swing.JLabel divider1_label3;
    private javax.swing.JPanel divider2;
    private javax.swing.JPanel divider3;
    private javax.swing.JPanel divider4;
    private javax.swing.JPanel draw_edge_mode_button;
    private javax.swing.JPanel draw_edge_mode_button2;
    private javax.swing.JPanel draw_edge_mode_button6;
    private javax.swing.JLabel draw_edge_mode_label;
    private javax.swing.JLabel draw_edge_mode_label2;
    private javax.swing.JLabel draw_edge_mode_label34;
    private javax.swing.JPanel draw_node_mode_button;
    private javax.swing.JPanel draw_node_mode_button2;
    private javax.swing.JLabel draw_node_mode_label;
    private javax.swing.JLabel draw_node_mode_label2;
    private javax.swing.JLabel feedback_label;
    private javax.swing.JPanel header;
    private javax.swing.JButton help;
    private javax.swing.JTextField init_node_name_input;
    private javax.swing.JLabel init_node_name_label;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel mode_label;
    private javax.swing.JPanel opt_container;
    private javax.swing.JTextArea output_textarea;
    private javax.swing.JLabel title_label;
    private javax.swing.JPanel undraw_node_mode_button;
    private javax.swing.JPanel undraw_node_mode_button2;
    private javax.swing.JPanel undraw_node_mode_button3;
    private javax.swing.JLabel undraw_node_mode_label;
    private javax.swing.JLabel undraw_node_mode_label2;
    private javax.swing.JLabel undraw_node_mode_label3;
    // End of variables declaration//GEN-END:variables
}
