package interfaces;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import sketch.GraphSketch;


public class ControlInterface extends javax.swing.JFrame {

    GraphSketch graphSketch;
    
    private final Color MAIN_COLOR = new Color(180, 10, 9);
    private final Color PRIMARY_TEXT = new Color(33, 33, 33);
    private final Color BACKGROUND_COLOR = new Color(247, 247, 250);
    private boolean[] activeButtonGroup = {true, false, false};
    private javax.swing.JPanel[] buttonGroup;
    private javax.swing.JLabel[] labelGroup;
    
    public ControlInterface() {
        initComponents();
        
        graphSketch = new GraphSketch();
        graphSketch.run();
        
        buttonGroup = new javax.swing.JPanel[]{
            draw_node_mode_button, 
            draw_edge_mode_button,
            undraw_node_mode_button,
        };
        labelGroup = new javax.swing.JLabel[]{
            draw_node_mode_label, 
            draw_edge_mode_label,
            undraw_node_mode_label,
        };

        centreWindows();
        updateButtonGroup(0);
    }

    public void updateButtonGroup(int activeIndex) {
        activeButtonGroup[activeIndex] = true;
        for (int i = 0; i < activeButtonGroup.length; i++) {
            activeButtonGroup[i] = false;
            if (i == activeIndex){
                activeButtonGroup[i] = true;
            }
        }
        for (int i = 0; i < activeButtonGroup.length; i++) {
            if (activeButtonGroup[i]){
                buttonGroup[i].setBackground(MAIN_COLOR);
                labelGroup[i].setForeground(Color.WHITE);
            }else{
                buttonGroup[i].setBackground(BACKGROUND_COLOR);
                labelGroup[i].setForeground(PRIMARY_TEXT);
            }
        }
    }
    
    private void centreWindows() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();

        int windownsGap = 30;
        int horizontalGap =  (int) ((dimension.getWidth() - 
            graphSketch.SKETCH_WIDTH - this.getWidth() - windownsGap) / 2);
        
        this.setLocation(horizontalGap, (int) 
            ((dimension.getHeight() - this.getHeight()) / 2));
        
        graphSketch.getSurface().setLocation(
            horizontalGap + this.getWidth() + windownsGap, 
            (int) ((dimension.getHeight() - graphSketch.SKETCH_HEIGHT) / 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        title_label = new javax.swing.JLabel();
        divider1 = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        divider1_label = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        command_input_container = new javax.swing.JPanel();
        command_input_label = new javax.swing.JLabel();
        command_input = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        draw_node_mode_button = new javax.swing.JPanel();
        draw_node_mode_label = new javax.swing.JLabel();
        draw_edge_mode_button = new javax.swing.JPanel();
        draw_edge_mode_label = new javax.swing.JLabel();
        undraw_node_mode_button = new javax.swing.JPanel();
        undraw_node_mode_label = new javax.swing.JLabel();
        command_input_label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 249, 249));

        header.setBackground(new java.awt.Color(136, 1, 1));

        title_label.setBackground(new java.awt.Color(55, 71, 79));
        title_label.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        title_label.setForeground(new java.awt.Color(255, 255, 255));
        title_label.setText("Servicio de internet");
        title_label.setIconTextGap(15);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(title_label)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(title_label)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        divider1.setBackground(new java.awt.Color(248, 249, 250));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(117, 117, 117));

        divider1_label.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        divider1_label.setForeground(new java.awt.Color(117, 117, 117));
        divider1_label.setText("Creación del grafo");

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator8.setForeground(new java.awt.Color(117, 117, 117));

        javax.swing.GroupLayout divider1Layout = new javax.swing.GroupLayout(divider1);
        divider1.setLayout(divider1Layout);
        divider1Layout.setHorizontalGroup(
            divider1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divider1Layout.createSequentialGroup()
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divider1_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8))
        );
        divider1Layout.setVerticalGroup(
            divider1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, divider1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(divider1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divider1_label)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        command_input_container.setBackground(new java.awt.Color(248, 249, 250));
        command_input_container.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        command_input_label.setBackground(new java.awt.Color(248, 249, 250));
        command_input_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        command_input_label.setForeground(new java.awt.Color(33, 33, 33));
        command_input_label.setText("Nombre o peso");
        command_input_label.setIconTextGap(12);
        command_input_container.add(command_input_label);

        command_input.setEditable(false);
        command_input.setBackground(new java.awt.Color(255, 255, 255));
        command_input.setColumns(7);
        command_input.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        command_input.setForeground(new java.awt.Color(33, 33, 33));
        command_input.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        command_input.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 189, 189)), javax.swing.BorderFactory.createEmptyBorder(7, 7, 7, 7)));
        command_input.setMargin(new java.awt.Insets(10, 10, 10, 10));
        command_input.setName(""); // NOI18N
        command_input_container.add(command_input);

        jPanel2.setBackground(new java.awt.Color(247, 250, 250));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        draw_node_mode_button.setBackground(new java.awt.Color(180, 10, 9));
        draw_node_mode_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        draw_node_mode_button.setName("Home"); // NOI18N
        draw_node_mode_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onDrawNode(evt);
            }
        });
        draw_node_mode_button.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        draw_node_mode_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        draw_node_mode_label.setForeground(new java.awt.Color(255, 255, 255));
        draw_node_mode_label.setText("Agregar Nodo");
        draw_node_mode_label.setIconTextGap(15);
        draw_node_mode_button.add(draw_node_mode_label);

        jPanel2.add(draw_node_mode_button);

        draw_edge_mode_button.setBackground(new java.awt.Color(180, 10, 9));
        draw_edge_mode_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        draw_edge_mode_button.setName("Home"); // NOI18N
        draw_edge_mode_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnDrawEdge(evt);
            }
        });
        draw_edge_mode_button.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        draw_edge_mode_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        draw_edge_mode_label.setForeground(new java.awt.Color(255, 255, 255));
        draw_edge_mode_label.setText("Agregar Arsita");
        draw_edge_mode_label.setIconTextGap(15);
        draw_edge_mode_button.add(draw_edge_mode_label);

        jPanel2.add(draw_edge_mode_button);

        undraw_node_mode_button.setBackground(new java.awt.Color(180, 10, 9));
        undraw_node_mode_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        undraw_node_mode_button.setName("Home"); // NOI18N
        undraw_node_mode_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onUnDrawNode(evt);
            }
        });
        undraw_node_mode_button.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 10));

        undraw_node_mode_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        undraw_node_mode_label.setForeground(new java.awt.Color(255, 255, 255));
        undraw_node_mode_label.setText("Remover Nodo");
        undraw_node_mode_label.setIconTextGap(15);
        undraw_node_mode_button.add(undraw_node_mode_label);

        jPanel2.add(undraw_node_mode_button);

        command_input_label1.setBackground(new java.awt.Color(248, 249, 250));
        command_input_label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        command_input_label1.setForeground(new java.awt.Color(33, 33, 33));
        command_input_label1.setText("Modos");
        command_input_label1.setIconTextGap(12);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(divider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(command_input_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(command_input_container, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(divider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(command_input_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(command_input_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(362, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onDrawNode(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onDrawNode
        updateButtonGroup(0);
    }//GEN-LAST:event_onDrawNode

    private void OnDrawEdge(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnDrawEdge
        updateButtonGroup(1);
    }//GEN-LAST:event_OnDrawEdge

    private void onUnDrawNode(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onUnDrawNode
        updateButtonGroup(2);
    }//GEN-LAST:event_onUnDrawNode

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField command_input;
    private javax.swing.JPanel command_input_container;
    private javax.swing.JLabel command_input_label;
    private javax.swing.JLabel command_input_label1;
    private javax.swing.JPanel divider1;
    private javax.swing.JLabel divider1_label;
    private javax.swing.JPanel draw_edge_mode_button;
    private javax.swing.JLabel draw_edge_mode_label;
    private javax.swing.JPanel draw_node_mode_button;
    private javax.swing.JLabel draw_node_mode_label;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel title_label;
    private javax.swing.JPanel undraw_node_mode_button;
    private javax.swing.JLabel undraw_node_mode_label;
    // End of variables declaration//GEN-END:variables
}
